AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer': {}
Parameters:
  EmailId:
    Type: String
    Description: Email for notification
Resources:
  MySNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: !Ref EmailId
          Protocol: email
  EventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: EventRule
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - ec2.amazonaws.com
          eventName:
            - TerminateInstances
            - DeleteVolume
      State: ENABLED
      Targets:
        - Arn: !Ref MySNSTopic
          Id: SNSTopic
          InputTransformer:
            InputTemplate: >
              "Cloudtrail recorded an event <eventName> 
              in Region <awsRegion> in the account"
            InputPathsMap:
              awsRegion: $.detail.awsRegion
              eventName: $.detail.eventName
              eventTime: $.detail.eventTime
  EventTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: '*'
      Topics:
        - !Ref MySNSTopic